<?php
    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = $this->zoneconfig['conf']['id'];
    $data_melisKey = $this->melisKey;
    $file = '';
    $icon = $this->docId ? 'pencil' : 'plus';
    $scheme = $this->scheme;
    $domain = $this->host;
    $images = $this->images;
    $title  = $this->title;
    $form  = $this->categoryMediaForm;
    if ($this->fileType == 'image') {
        $title = "Image";
    } else {
        $title = "tr_meliscms_categories_media_select_file";
    }

?>
<div class="modal-content" id="<?= $id; ?>"  data-melisKey="<?= $data_melisKey; ?>" style="position: relative;">
    <div class="modal-body padding-none">
        <div class="wizard">
            <div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head" style="cursor: move">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="glyphicons plus" data-toggle="tab" aria-expanded="true" style="cursor: move;"><i></i><?php echo $this->translate($title) ?></a></li>
                    </ul>
                </div>
                <div class="widget-body innerAll inner-2x">
                    <div class="tab-content">
                        <div class="tab-pane active" <?php echo $id ?>>
                            <div class="mini-media-library">
                                <h3><?= $this->translate('tr_meliscms_categories_media_heading');?></h3>
                                <div class="min-upload-image">
                                    <p><i class="fa fa-upload"></i> <?= $this->translate('tr_meliscms_categories_upload_text')?></p>
                                    <p> <?= $this->translate('tr_meliscms_categories_media_sub_heading');?> : <a href="/media/categories/" target="_blank">/media/categories</a></p>
                                    <?php
                                        $form->prepare();
                                        echo $this->form()->openTag($form);
                                        echo $this->melisFieldCollection($form);
                                    ?>
                                    <br>
                                    <button type="submit" class="btn btn-success pull-right" id="category-upload-media" data-target-area="<?= $this->targetDiv ?>"   data-type="<?= $this->fileType ?>"><i class="fa fa-upload" data-type="<?= $this->fileType ?>"></i> <?= $this->translate('tr_meliscms_categories_media_upload_btn')?> </button>
                                    <?php
                                        echo $this->form()->closeTag($form);
                                    ?>
                                    <script>
                                        $(":file").filestyle({
                                            input: true,
                                            badge: true,
                                            size : "sm",
                                            buttonText: '<?php echo $this->translate('tr_meiscms_categories_media_choose_file')?>',
                                            classButton : 'btn btn-primary'
                                        });
                                    </script>
                                </div>
                                <br>
                                <div class="mini-image-list">
                                    <div class="row">
                                        <?php if (count($images) > 0) {?>
                                            <?php foreach ($images as $idx => $image) {?>
                                                <div class="col-md-3">
                                                    <?php if ($this->fileType == 'image') {?>
                                                        <div class="image-area">
                                                            <img src="/media/categories/<?= $image ?>" alt="<?= $image ?>" title="<?= $image?>" class="img-responsive">
                                                            <span class="description"><?= $image ?></span>
                                                            <div class="add-wrapper add-image" data-order="<?= $idx ?>" data-target-div="<?= $this->targetDiv ?>" data-file-type="image" data-image-url="/media/categories/<?= $image ?>" title="<?= $this->translate('tr_meliscms_categories_media_add_image')?> <?= $image ?>">
                                                                <i class="fa fa-plus"></i>
                                                            </div>
                                                        </div>
                                                    <?php } else {?>
                                                        <div class="file-area">
                                                            <span class="fa fa-file file-icon"></span>
                                                            <span class="description"><?= $image ?></span>
                                                            <div class="add-wrapper add-image" data-order="<?= $idx ?>" data-target-div="<?= $this->targetDiv ?>" data-file-type="file" data-image-url="/media/categories/<?= $image ?>" title="<?= $this->translate('tr_meliscms_categories_media_add_file')?> <?=$image?>">
                                                                <i class="fa fa-plus"></i>
                                                            </div>
                                                        </div>
                                                    <?php }?>
                                                </div>
                                            <?php }?>
                                        <?php } else {?>
                                            <?php if ($this->fileType == 'image') {?>
                                                <span class="no-file"><?= $this->translate('tr_melis_cms_category_empty_media_image');?></span>
                                            <?php } else {?>
                                                <span class="no-file"><?= $this->translate('tr_melis_cms_category_empty_media_file');?></span>
                                            <?php }?>
                                        <?php }?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <?php
                            $targetDiv = null;
                            if ($this->fileType == 'image') {
                                $targetDiv = ".parent-file-list";
                            } else {
                                $targetDiv = ".parent-image-list";
                            }
                        ?>
                        <div class="buttons">
                            <button data-dismiss="modal" id="closeMedialibrary" data-target-remove-backdrop ="<?= $targetDiv ?>"  class="btn btn-danger pull-left"><i class="fa fa-times"></i> <?= $this->translate('tr_meliscore_common_close')?></button>
                        </div>
                        <div class="clearfix"></div>
                        <div class="media-upload-loader">
                            <div id="loader" class="overlay-loader"><img class="loader-icon spinning-cog" src="/MelisCore/assets/images/cog12.svg" data-cog="cog12"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
