<?php
    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = $this->zoneconfig['conf']['id'];
    $data_melisKey = $this->melisKey;
    $file = '';
    $icon = $this->docId ? 'pencil' : 'plus';
    $scheme = $this->scheme;
    $domain = $this->host;
    $images = $this->images;
    $title  = $this->title;
    $title = "Select image";
    $form  = $this->categoryMediaForm;
?>
<div class="modal-content" id="<?= $id; ?>" data-melisKey="<?= $data_melisKey; ?>">
    <div class="modal-body padding-none">
        <div class="wizard">
            <div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="glyphicons <?= $icon; ?>" data-toggle="tab" aria-expanded="true"><i></i> <?php echo $this->translate($this->title) ?></a></li>
                    </ul>
                </div>
                <div class="widget-body innerAll inner-2x">
                    <div class="tab-content">
                        <div class="tab-pane active" <?php echo $id ?>>
                            <div class="mini-media-library">
                                <h3>Media library</h3>
                                <p> Directory : <a href="/media" target="_blank">/media</a></p>
                                <div class="min-upload-image">
                                    <p>Upload your media files here </p>
                                    <?php
                                        $form->prepare();
                                        echo $this->form()->openTag($form);
                                        echo $this->melisFieldCollection($form);
                                    ?>
                                    <br>
                                    <button type="submit" class="btn btn-primary pull-right" id="category-upload-media" data-type="<?= $this->fileType ?>"><i class="fa fa-upload"></i> Upload</button>
                                    <?php
                                        echo $this->form()->closeTag($form);
                                    ?>
                                    <script>
                                        $(":file").filestyle({
                                            buttonBefore: true,
                                            input: true,
                                            badge: true,
                                            size : "sm",
                                            text: '<?php echo $this->translate('tr_meliscms_user_account_input_file')?>'
                                        });
                                    </script>
                                </div>
                                <br>
                                <div class="mini-image-list">
                                    <div class="row">
                                        <?php foreach ($images as $idx => $image) {?>
                                            <div class="col-md-3">
                                                <?php if ($this->fileType == 'image') {?>
                                                    <div class="image-area">
                                                        <img src="/media/<?= $image ?>" alt="<?= $image ?>" title="<?= $image?>" class="img-responsive">
                                                        <span class="description"><?= $image ?></span>
                                                        <div class="add-wrapper add-image" data-order="<?= $idx ?>" data-image-url="/media/<?= $image ?>" title="Add image <?= $image ?>">
                                                            <i class="fa fa-plus"></i>
                                                        </div>
                                                    </div>
                                                <?php } else {?>
                                                    <div class="file-area">
                                                        <span class="fa fa-file file-icon"></span>
                                                        <span class="description"><?= $image ?></span>
                                                        <div class="add-wrapper add-image" data-order="<?= $idx ?>" data-image-url="/media/<?= $image ?>" title="Add <?= $image?>">
                                                            <i class="fa fa-plus"></i>
                                                        </div>
                                                    </div>
                                                <?php }?>
                                            </div>
                                        <?php }?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="buttons">
                            <button data-dismiss="modal" class="btn btn-danger pull-right"><i class="fa fa-times"></i> <?= $this->translate('tr_meliscore_common_close')?></button>                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
