<?php
    $id = '';
    $relationType = '';

    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    if (!empty($this->zoneconfig['conf']['docRelationType'])){
        $relationType = $this->zoneconfig['conf']['docRelationType'];
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>

<div <?php echo $id. ' '.$data_melisKey?> class="ecom-doc-container" data-doc-relation-type="<?= $relationType; ?>" data-doc-relation-id="<?= $this->relationId; ?>" data-doc-type="file">
	<div class="clearfix">
		<h4>
			<i class="fa fa-paperclip"></i> <?php echo $this->translate('tr_meliscategory_documents_file_attachments')?>
		</h4>
        <button class="btn btn-primary pull-right category-add-file" data-type="file">
            <i class="fa fa-folder-open"></i>
            <?php echo $this->translate('Browse media')?>
        </button>
        <div class="category-file-list row">
        <?php
            # file count
            $fileCount = $this->fileCount;
            if(!empty($fileCount)) {?>

            <?php } else {?>
                No file added
            <?php }?>
        </div>
	</div>
</div>
