<?php
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'" ';
    }
    $idLen = $this->docRelationType.$this->docRelationId;
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
    $media = $this->mediaData;
    $currentPosition = 0;
?>
<div <?= $id . $data_melisKey; ?>>
	<div class="row">
        <div class="parent-image-list">
            <div class="category-image-list row">
                <?php if (! empty($media)) {?>
                    <?php foreach ($media as $key => $data) {
                            $path = $data['catm2_path'] ?? null; ?>
                        <?php if ($data['catm2_type'] == 'image' ){?>
                            <div class="col-md-12 margin-b-10 category-image">
                                <img src="<?= $path ?>" class="img-responsive"/>
                                <input type="hidden" value="<?= $path ?>">
                                <div class="category-image-option">
                                    <a class="viewImage" target="_blank" href="<?= $path ?>"> <i class='fa fa-eye' title='View image'></i></a>
                                    <a class="removeImage"  href="#"><i class='fa fa-times' title='Delete image'></i></a>
                                </div>
                            </div>
                            <?php $currentPosition = $currentPosition + 1;?>
                        <?php }?>
                    <?php }?>
                <?php } else {?>
                    <span class="no-image">No image</span>
                <?php }?>
                <!-- add to button attribute browse mediacurrent position -->
                <script>
                    $(".category-add-image").attr('data-currentposition',<?= $currentPosition ?>);
                </script>
            </div>
            <div class="back-drop"></div>
        </div>
	</div>
</div>
