<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
    $currentPosition = 0;
?>
<div <?php echo $id. ' '.$data_melisKey?>>
	<div class="pdc-heading clearfix">
		<h4>
			<i class="fa fa-image"></i>
			<?php echo $this->translate('tr_meliscategory_documents_product_imgs')?>
		</h4>
		<button class="btn btn-success pull-right category-add-image" data-type="image">
			<i class="fa fa-plus"></i>
			<?php echo $this->translate('tr_meliscms_categories_add_image')?>
		</button>
	</div>	

</div>					

<?php 
    if(!empty($this->zoneconfig['interface'])) {
        foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
            echo $this->$keyConfig;
        }
    }
?>
