<?php
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'" ';
    }
    $idLen = $this->docRelationType.$this->docRelationId;
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
    $media = $this->categoryMediaData;
?>
<div <?= $id . $data_melisKey; ?>>
	<div class="row">

        <?php if (! empty($media)) {?>

        <?php } else {?>
            <span class="no-image">No image</span>
        <?php }?>
        <div class="category-image-list row">

        </div>
	</div>
</div>
