<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'].'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div class="tab-pane " <?php echo $id. ' '.$data_melisKey?>>
	<?php 
    	if(!empty($this->zoneconfig['interface'])) {
    	    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
    	        echo $this->$keyConfig.' ';
    	    }
    	}
    ?>
    <!--<div>
        <span class="scroll-to-top visible text-primary" id="categoryScrollToTop">
            <i class="fa fa-arrow-up"></i>
        </span>
        <div class="clearfix"></div>
    </div>-->
    <script>
        var heightContent = $("#id_meliscategory_category_tab_media").height();
        if (heightContent <= 628) {
            $("#categoryScrollToTop").fadeOut();
        } else {
            $("#categoryScrollToTop").fadeIn();
        }
    </script>
</div>
