<?php
    $pluginData = $this->pluginData ?? null;
    $categoryData = $this->cmsCategoryTreeData ?? null;
    $renderMode = $pluginData['renderMode'];
    $previewMode = $pluginData['previewMode'];
    $siteId = $pluginData['site_id'];

?>
<?php if ($renderMode == 'front' || $previewMode == true) { ?>
<div class="<?php echo "$this->widthDesktop $this->widthTablet $this->widthMobile" ?>" >
    <?php } else { ?>
<div>
    <?php } ?>
    <div class="melis-cms-categories-display" id="melis-cms-categories-display-<?=$pluginData['id']?>>" data-plugin-id="<?=$pluginData['id']?>">
        <?php if (! empty($siteId)) {?>
<!--            <div class="alert alert-info">-->
<!--            </div>-->
        <?php } ?>
        <ul>
            <?= $this->renderTreeRec($categoryData); ?>
        </ul>

    </div>
</div>
