-- MySQL Script generated by MySQL Workbench
-- Tue Mar 12 13:51:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `melis_cms_category2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_cms_category2_media` ;
DROP TABLE IF EXISTS `melis_cms_category2_trans` ;
DROP TABLE IF EXISTS `melis_cms_category2_sites` ;
DROP TABLE IF EXISTS `melis_cms_category2` ;

CREATE TABLE IF NOT EXISTS `melis_cms_category2` (
  `cat2_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Category Id',
  `cat2_father_cat_id` INT NOT NULL DEFAULT -1 COMMENT 'Parent Id of a category',
  `cat2_order` INT NOT NULL COMMENT 'Order display of category',
  `cat2_status` TINYINT NOT NULL COMMENT 'Status : active / inactive',
  `cat2_reference` VARCHAR(45) NULL COMMENT 'Reference of the category',
  `cat2_date_valid_start` DATETIME NULL COMMENT 'Starting date for showing the category',
  `cat2_date_valid_end` DATETIME NULL COMMENT 'Ending date for showing the category',
  `cat2_date_creation` DATETIME NOT NULL,
  `cat2_user_id_creation` INT NOT NULL,
  `cat2_date_edit` DATETIME NULL,
  `cat2_user_id_edit` INT NULL,
  PRIMARY KEY (`cat2_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melis_cms_category2_trans`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `melis_cms_category2_trans` (
  `catt2_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Category translation Id',
  `catt2_category_id` INT NOT NULL COMMENT 'Category Id',
  `catt2_lang_id` INT NOT NULL COMMENT 'Language id',
  `catt2_name` VARCHAR(100) NOT NULL COMMENT 'Name of the category in the given language',
  `catt2_description` TEXT NULL COMMENT 'Description of the category in the given language',
  PRIMARY KEY (`catt2_id`),
  CONSTRAINT `trans_relation_id`
    FOREIGN KEY (`catt2_category_id`)
    REFERENCES `melis_cms_category2` (`cat2_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `relationId_idx` ON `melis_cms_category2_trans` (`catt2_category_id` ASC);


-- -----------------------------------------------------
-- Table `melis_cms_category2_sites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_cms_category2_sites` (
  `cats2_id` INT NOT NULL AUTO_INCREMENT,
  `cats2_site_id` INT NOT NULL,
  `cats2_cat2_id` INT NOT NULL,
  PRIMARY KEY (`cats2_id`),
  CONSTRAINT `sites_relation_id`
    FOREIGN KEY (`cats2_cat2_id`)
    REFERENCES `melis_cms_category2` (`cat2_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `relationId_idx` ON `melis_cms_category2_sites` (`cats2_cat2_id` ASC);


-- -----------------------------------------------------
-- Table `melis_cms_category2_media`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `melis_cms_category2_media` (
  `catm2_id` INT NOT NULL AUTO_INCREMENT,
  `catm2_type` VARCHAR(100) NOT NULL,
  `catm2_path` VARCHAR(200) NOT NULL,
  `catm2_cat_id` INT NOT NULL,
  PRIMARY KEY (`catm2_id`),
  CONSTRAINT `media_relation_id`
    FOREIGN KEY (`catm2_cat_id`)
    REFERENCES `melis_cms_category2` (`cat2_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `relationId_idx` ON `melis_cms_category2_media` (`catm2_cat_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
