<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div class="col-xs-12 col-lg-8" <?php echo $id. ' '.$data_melisKey?>>
	<div class="cat-tree-view-languages filter-dropdown clearfix">
		<a href="#" class="dropdown-toggle category-list-lang-dropdown" data-toggle="dropdown" data-locale="<?php echo $this->currentLangName ?>">
			<?php //echo $this->currentLangImg; ?>
			<i class="fa fa-language"></i>
			<span class="filter-key"><?php echo $this->currentLangName; ?></span>
			<span class="caret"></span>
		</a>
		<ul class="dropdown-menu category-tree-view-lang">
			<?php foreach ($this->cmsLang As $val):?>
    			<li>
    				<a data-locale="<?php echo $val['lang_cms_locale']?>">
                        <span><?php echo $val['lang_cms_name']?></span>
                        <span class="pull-right">
                            <img src="/MelisCms/images/lang-flags/<?= $val['lang_cms_locale']?>.png" alt="">
                        </span>
                    </a>
    			</li>
			<?php endforeach;?>
		</ul>
	</div>
	<div class="cat-div" style="display: inline-block;">
		<div class="alert alert-warning hidden" id="searchNoResult">"<strong></strong>" <?php echo $this->translate('tr_meliscmscategory_search_not_found')?></div>
		<div class="alert alert-warning " id="noResultData"><strong><?php echo $this->translate('No data found')?></strong></div>
		<div id="categoryTreeView" data-langlocale="<?php echo $this->currentLangLocale ?>"></div>
	</div>

</div>