 <?php
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div class="card-heading" style="height: initial;padding:0;border-bottom:1px solid #eee;" <?php echo $id.' '.$data_melisKey; ?> >
	<div class="card-title" style="margin-top: inherit;">
		<div class="card-heading-buttons float-right">
			<?php
            	if(!empty($this->zoneconfig['interface'])) {
            	    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
            	        echo $this->$keyConfig;
            	    }
            	}
            ?>
        </div>
		<a class="accordion-toggle" data-bs-toggle="collapse" data-bs-target="#cmsCategoryTreeViewPanel">
			<h1 class="content-heading"><?php echo ucfirst($this->translate('tr_melis_cms_category_v2_header_title'))?>
				<span class="custom-category-desc"><?= ucfirst($this->translate('tr_melis_cms_category_v2_header_sub_title'));?></span>
			</h1>
		</a>
	</div>
</div>