<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div class="col-xs-12 col-lg-12" <?php echo $id.' '.$data_melisKey; ?> style="margin-top:20px;">
    <h4><?= $this->translate('tr_meiscms_categories_fitler_site_heading');?></h4>
	<?php
    	$form = $this->meliscategory_site_filer_form;
    	$form->prepare();
    	echo $this->form()->openTag($form);
    	echo $this->melisFieldCollection($form);
    	echo $this->form()->closeTag();
    ?>
    <p class="info-site-filter "><?= $this->translate('tr_melis_cms_categories_affected_to_site_message')?></p>
</div> 