<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
    $categorySites = $this->cartegorySites;
    $siteData      = $this->siteData;
?>
<div <?php echo $id. ' '.$data_melisKey?> >
	<div class="form-group">
    	<div class="row">
    		<div class="col-xs-12">
    			<div class="pdc-heading clearfix">
                    <h4>
                    	<i class="fa fa-globe"></i> <?php echo $this->translate('tr_meliscategory_categories_category_countries')?>
                    </h4>
                </div>
    		</div>
    		<form>
        		<?php 
        		    $checked = '';
        		    if (count($siteData) == count($categorySites)){
        		        $checked = 'check';
        		    }
        		?>
        		<div class="col-xs-4">
                	<label class="cms-category-checkbox">
                		<i class="fa fa-<?php echo ($checked) ? $checked.'-' : '' ?>square-o fa-lg check-all"></i> <?php echo $this->translate('tr_meliscategory_categories_common_label_all')?>
                		<input type="checkbox" name="cat_sites[]" value="-1" <?php echo ($checked) ? $checked.'ed' : '' ?>>
                	</label>
        		</div>
        		<?php foreach ($siteData As $val):?>
        			<?php
        			    $checked = '';
        			    if (!empty($categorySites)){
        			        if(in_array($val['site_id'], $categorySites) || in_array('-1', $categorySites)){
        			            $checked = 'check';
        			        }
        			    }
        			?>
        			<div class="col-xs-4">
                    	<label class="cms-category-checkbox">
                    		<i class="fa fa-<?php echo ($checked) ? $checked.'-' : '' ?>square-o fa-lg"></i> <?php echo !empty($val['site_label']) ? $val['site_label'] : $val['site_name']?>
                    		<input type="checkbox" name="cat_sites[]" value="<?php echo $val['site_id']?>" <?php echo ($checked && !in_array('-1', $categorySites)) ? $checked.'ed' : '' ?>>
                    	</label>
            		</div>
        		<?php endforeach;?>
    		</form>
    	</div>
	</div>
</div>