<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
    $languageToSelect = $this->currentLocale;
?>
<div <?php echo $id. ' '.$data_melisKey?> >
	<div class="row">
		<div class="col-xs-12 col-md-5 col-lg-4">
			<div class="pdc-heading clearfix">
				<h3>
					<i class="fa fa-cog"></i> <?php echo $this->translate('tr_meliscategory_categories_common_label_texts')?>
				</h3>
			</div>
    		<div class="product-text-tab-container">
            	<ul class="nav-tabs product-text-tab">
            		<?php foreach ($this->ecomLang as $key => $val){;?>
                		<li class="">
                			<a class="clearfix" data-toggle="tab" href="#<?php echo $val['lang_cms_name'].'_categoryInfo' ?>" aria-expanded="false">
								<?php
								    $langLocale = $val['lang_cms_locale'] ?? null;
                                    echo '<span class="float-right"><img src="/MelisCms/images/lang-flags/' . $langLocale .'.png" class="imgDisplay float-right"/></span>';
                                ?>
                				<span><?php echo $val['lang_cms_name']?></span>
                			</a>
                		</li>
            		<?php }?>
            	</ul>
            </div>
		</div>
		<div class="col-xs-12 col-md-7 col-lg-8">
			<div class="tab-content">
				<?php  foreach ($this->ecomLang As $key => $val):?>
					<div id="<?php echo $val['lang_cms_name'].'_categoryInfo' ?>" class="tab-pane product-text-tab-content">
    					<div class="me-heading bg-white ">
                			<h3 class=""><i class="fa fa-language" aria-hidden="true"></i> <?php echo $val['lang_cms_name']?></h3>
                		</div>
                		<div class="product-text-tab-form-content" style="padding-bottom: 0px; padding-right: 0px;">
            				<?php
                            	$form = clone $this->meliscommerce_categories_category_information_form;
                            	$form->setData($this->formDefaultValues);
                            	$form->setAttribute('class','cat_trans_form');
                            	$form->setAttribute('data-langid', $val['lang_cms_id']);
                            	$form->get('catt2_lang_id')->setValue($val['lang_cms_id']);

                            	if (!empty($this->categoryTrans))
                            	{
                            	    foreach ($this->categoryTrans As $cVal)
                            	    {

                            	        if ($cVal->lang_cms_id == $val['lang_cms_id'])
                            	        {
                            	            $form->bind($cVal);
                            	        }
                            	    }
                            	}
                            	$form->prepare();
                            	echo $this->form()->openTag($form);
                            	echo $this->melisFieldCollection($form);
                            	echo $this->form()->closeTag();
                            ?>
                        </div>
                    </div>
                <?php endforeach;?>
			</div>
		</div>
	</div>
    <script type="text/javascript">
		$(function() {
			var $body = $("body"),
				option = {
					// mode: "none",
					height: "300px",
					plugins: [
						'lists', 'advlist', 'autolink', 'link', 'image', 'charmap', 'preview', 'anchor',
						'searchreplace', 'visualblocks', 'code', 'fullscreen',
						'insertdatetime', 'media', 'table'
					],
					// styleselect = styles
					toolbar: 'undo redo | styles | bold italic |  alignleft aligncenter alignright alignjustify | forecolor backcolor | code',
				},
				/* Fixes issue: https://mantis2.uat.melistechnology.fr/view.php?id=4906
				 * Added back the default toolbar option on createTinyMCE .editme on .close-tab #close-all-tab
				 */
				defaultOption = {
					height: "300px",
					plugins: [
						'lists', 'advlist', 'autolink', 'link', 'image', 'charmap', 'preview', 'anchor', 'help', 'nonbreaking',
						'searchreplace', 'visualblocks', 'code', 'fullscreen', 'insertdatetime', 'media', 'table', 'minitemplate' 
					],
					toolbar: 'insertfile undo redo | blocks | forecolor | bold italic strikethrough underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media | minitemplate code',
				};

				melisTinyMCE.createTinyMCE("toolTranslate", ".editme", option);
				
				$body.on("click", ".close-tab", function() {
					if ( $(this).attr("data-id") === "id_meliscommerce_categories_page" ) {
						melisTinyMCE.createTinyMCE("tool", ".editme", defaultOption);
					}
				});

				$body.on("click", "#close-all-tab", function() {
					melisTinyMCE.createTinyMCE("tool", ".editme", defaultOption);
				});
		});
    </script>
</div>