<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div <?php echo $id. ' '.$data_melisKey?> >
	<div class="row">
    	<div class="col-xs-12">	
        	<div class="pdc-heading clearfix">
                <h4>
                	<i class="fa fa-cog"></i> <?php echo $this->translate('tr_meliscategory_categories_common_label_texts')?>
                </h4>
            </div>
        </div>
		<div class="col-xs-12 col-md-5 col-lg-4">
    		<div class="product-text-tab-container">
            	<ul class="nav-tabs product-text-tab">
            		<?php foreach ($this->ecomLang as $key => $val){;?>
                		<li class="">
                			<a class="clearfix" data-toggle="tab" href="#<?php echo $val['lang_cms_name'].'_categoryInfo' ?>" aria-expanded="false">
								<?php
								    $langLocale = $val['lang_cms_locale'] ?? null;

                                    //if(!empty($imageData))
                                    //{
                                        echo '<span class="pull-right"><img src="/MelisCms/images/lang-flags/' . $langLocale .'.png" class="imgDisplay pull-right"/></span>';
                                    //}
//                                    else
//                                    {
//                                        echo '<i class="fa fa-globe"></i>';
//                                    }
                                ?>
                				<span><?php echo $val['lang_cms_name']?></span>
                			</a>
                		</li>
            		<?php }?>
            	</ul>
            </div>
		</div>
		<div class="col-xs-12 col-md-7 col-lg-8">
			<div class="tab-content">
				<?php  foreach ($this->ecomLang As $key => $val):?>
					<div id="<?php echo $val['lang_cms_name'].'_categoryInfo' ?>" class="tab-pane product-text-tab-content">
    					<div class="me-heading bg-white ">
                			<h3 class=""><i class="fa fa-language" aria-hidden="true"></i> <?php echo $val['lang_cms_name']?></h3>
                		</div>
                		<div class="product-text-tab-form-content" style="padding-bottom: 0px; padding-right: 0px;">
            				<?php
                            	$form = clone $this->meliscommerce_categories_category_information_form;
                            	$form->setData($this->formDefaultValues);
                            	$form->setAttribute('class','cat_trans_form');
                            	$form->setAttribute('data-langid', $val['lang_cms_id']);
                            	$form->get('catt2_lang_id')->setValue($val['lang_cms_id']);
                            	
                            	if (!empty($this->categoryTrans)) 
                            	{
                            	    foreach ($this->categoryTrans As $cVal)
                            	    {

                            	        if ($cVal->lang_cms_id == $val['lang_cms_id'])
                            	        {
                            	            $form->bind($cVal);
                            	        }
                            	    }
                            	}
                            	$form->prepare();
                            	echo $this->form()->openTag($form); 
                            	echo $this->melisFieldCollection($form);
                            	echo $this->form()->closeTag(); 
                            ?>
                        </div>
                    </div>
                <?php endforeach;?>
			</div>
		</div>
	</div>
    <script type="text/javascript">
        var option = {
            mode : "none",
            height : "300px",
            plugins : [
                'advlist autolink lists link image charmap print preview anchor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table contextmenu paste template',
                'textcolor',
            ],
            toolbar : 'undo redo | styleselect | bold italic |  alignleft aligncenter alignright alignjustify | forecolor backcolor | code',
        }
        melisTinyMCE.createTinyMCE("tool", ".editme", option);
    </script>
</div>